#!/bin/sh -ex

. inc/common

juju-log "Installing software"

ver=$(config-get [version])

juju-log $ver

if [ $ver = 2.0.0.0 ]; then
   juju-log "version 2.0.0.0 not instal"
   echo "VERSION 2.0.0.0"
   exit 0
fi

juju-lo "No version"

apt-get update
apt-get -y install --no-install-suggests --no-install-recommends  apache2 php5-gd libapache2-mod-php5 mysql-client-core-5.5 php5-mysql pwgen php5-curl php5-mcrypt exim4-daemon-light

sed -i "s|dc_eximconfig_configtype='local'|dc_eximconfig_configtype='internet'|g" /etc/exim4/update-exim4.conf.conf

update-exim4.conf

a2enmod php5 headers
a2dissite 000-default

php5enmod mcrypt
php5enmod curl

service apache2 restart

juju-log "Download"
OC_TARBALL="https://github.com/opencart/opencart/archive/1.5.6.4.tar.gz"
OC_MD5SUM="a783a14939afaaf33040a1decffccbae"
curl -vv -L $OC_TARBALL > /tmp/opencart.tar.gz

juju-log "Extract"
mkdir -p $install_path
tar --strip-components=2 --wildcards -C $install_path -zxf /tmp/opencart.tar.gz opencart-*/upload
rm -f /tmp/opencart.tar.gz
mv $install_path/.htaccess.txt $install_path/.htaccess

(
patch -d $install_path -p1 < files/opencart/default_db.patch
)

# Secret key for configuring OpenCart
#secret_key=`pwgen 32 1`
#sed -i "s|public \$secret = '.*';|public \$secret = '"$secret_key"';|g" $install_path/installation/configuration.php-dist

# Set better file permissions
set_permissions
